import "./globals.css";
import "@/src/app/themes_colors/default.css";
import { Inter } from "next/font/google";

import MenuContextProvider from "@/src/app/(context)/MenuContext";
import { ColorProvider } from "@/src/app/(context)/ColorContext";
import { ActiveStepProvider } from "@/src/app/(context)/ActiveStepContext";
import { ConfigProvider } from "antd";
import { AuthenticationProvider } from "./(context)/authentication-context";
import StyledComponentsRegistry from "../lib/AntRegistry";
import { AccountStatementContextProvider } from "./(context)/account-statement-context";

export const metadata = {
  title: "kcb || Statement-App",
  description: "Generated by create next app",
  icons: {
    icon: '/simbaportallogo.svg',
  }
};

const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className} lang="en">
      <head>
        <link rel="icon" href={metadata.icons.icon} sizes="any" />
      </head>
      <body>
        <AuthenticationProvider>
          <AccountStatementContextProvider>
            <ColorProvider>
              <ConfigProvider theme={{ hashed: false }}>
                <ActiveStepProvider>
                  <MenuContextProvider>
                    <StyledComponentsRegistry>
                      {children}
                    </StyledComponentsRegistry>
                  </MenuContextProvider>
                </ActiveStepProvider>
              </ConfigProvider>
            </ColorProvider>
          </AccountStatementContextProvider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
